#!/bin/sh

echo "---------------------------"
echo "  eggoez creating configuration files   "
echo "  visit at eg-goez.blogspot.com         "
echo "  or go #ciut irc.allnetwork.org         "
echo "---------------------------"
echo ""

if test $# -ne 7
then
  echo "Use  :"
  echo ""
  echo "   ./eggo 1 2 3 4 5 6 7"
  echo ""
  echo "   1 = new name file config will create"
  echo "   2 = nick bot will be use"
  echo "   3 = ident bot will be use"
  echo "   4 = IP Shell / VPS"
  echo "   5 = channel (dont enter #)"
  echo "   6 = nick owner"
  echo "   7 = Server IRC"
  echo ""
  exit
fi

if ! test -s .ge/goez.tcl
then
  echo "Error : goez.tcl not found."
  echo ""
  exit
fi

if ! test -s eggo.conf
then
  echo "Error : eggo.conf not found."
  echo ""
  exit
fi

if ! test -s .ge/goez.tcl
then
  echo "Ops.. needd file goez.tcl"
  echo "try to redownload eggoez.tar.gz"
  exit
fi

if ! test -s eggo.conf
then
  echo "Ops.. cant find eggo.conf eggoez.tar.gz need this file."
  echo "Please redonwload or contact us"
  exit
fi

echo "set nick "\"$2\" > $1
echo "set username "\"$3\" >> $1
echo "set my-hostname "\"$4\" >> $1
echo "set my-ip "\"$4\" >> $1
echo "set basechan "\"\#$5\" >> $1
echo "set owner "\"$6\" >> $1
echo "set servers "\{$7\} >> $1
echo " Config file : "$1""
cat $1
echo "set userfile "\"$2.usr\" >> $1
echo "set chanfile "\"$2.chn\" >> $1
echo "set altnick "\"$2--\" >> $1


cat eggo.conf >> $1
pwd > $1.dir
dir=$(cat $1.dir)
echo "* * * * * $dir/$1.upd >/dev/null 2>&1" > $1.d
crontab $1.d
crontab -l | grep $1.upd
echo "
if test -r $dir/pid.$1; then
pid=\$(cat $dir/pid.$1)
if \$(kill -CHLD \$pid >/dev/null 2>&1)
then
exit 0
fi
fi
cd $dir
./$1.run &>/dev/null" > $1.upd
chmod u+x $1.upd
echo "
./go -s "eggoez: running@eggdrop.goez -OK" ./eggoez -m $1
" > $1.run
chmod u+x $1.run
echo ""
echo ""

echo "Okay.. New file configuration was created."
echo "for run your bot syntax:"
echo "./goez $1 "
echo ""
echo "keep spirit frinds"
echo "thanks for use eggdrop goez"

